### PR TITLE
Add back ClientRect

### PR DESCRIPTION
**Pull request by orta**
( I can't comment in the JSON because that's in  #110 )

Roughly, this is used in ckeditor which triggers a gazillion fails across DT

### CODE REVIEW

**Comment by saschanaz** [comment]
ClientRect is just a legacy MS-specific name of [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect), so I'd just do `interface ClientRect extends DOMRect` with a deprecated flag.

**Review by saschanaz — CHANGES_REQUESTED** [review]
(As I said above)

**Comment by orta** [comment]
Updated this PR with comments etc. 

I'm a little unsure why there's a change with `CSSNumberish` - I can't find anything about it in the repo, and `main` shows as green  https://github.com/saschanaz/types-web/search?q=cssnumberish

**Comment by saschanaz** [comment]
I guess you need to do `npm i` to get latest deps 😄

**Pull request merged**
