### PR TITLE
Adds aliases for renamed HTML elements

### PR DESCRIPTION
**Pull request by orta**
The type which represents `td` and `th` changed in https://github.com/saschanaz/types-web/commit/3dcb74ecc701fbe8a30093bec749014547e5717#diff-d57c51d024219b9f37e6b42df127db25f700acbaade23ce1edcecda2853b995cL19148

Which meant that any downstream consumer who mapped over the known html types (basically JSX) would try accessing elements which don't exist. I'm also open to renaming that somewhere - still sorta getting my grips on this repo

### CODE REVIEW

**Comment by saschanaz** [comment]
LGTM but could you add deprecated flags too?

**Comment by saschanaz** [comment]
Also please set the correct `exposed` field values.

**Comment by orta** [comment]
Ah, that's how I scope it to just window!

**Comment by saschanaz** [comment]
Thanks! There is `deprecated` field for that but LGTM since it does not support any strings yet.

**Comment by orta** [comment]
Yeah, I added both, then figured it just made more sense to do the comment with it inline

**Pull request merged**
